
###
##nuevo OK

POST  http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "pruebaProyeAdmin3",
    "nombre":"prueba Proyecte",
    "email":"hectorproyeAdmin3@gmail.com",
    "password":"NoTeLoDigo@1"
   
}

###
##login OK

POST  http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "pruebaProyeAdmin3",
    "password":"NoTeLoDigo@1"
    
}

##Muestra Partidas
###
GET  http://localhost:8090/api/risk/partidas HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3OTg0MTI2LCJleHAiOjE3MDgwMjAxMjZ9.AUEvLA3yVdNKwEiVcg4uOxmrndQKdeBsA38JaCOkGos

##Muestra Salas
###
GET  http://localhost:8090/api/risk/salas HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluMyIsImlhdCI6MTcwNzk4NzAxNiwiZXhwIjoxNzA4MDIzMDE2fQ.2PeQ0m_u8Sqbqj6bYPl_-1YxCx1e3EjL0B33MLzf8cQ

##Muestra Zonas
###
GET  http://localhost:8090/api/risk/zonas HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3ODEzNTc0LCJleHAiOjE3MDc4NDk1NzR9.1G55su8c4Rm8N1TrV15kdn6I9ArwEEPRNZvfHry2qXs

##Muestra Partidas por ID
###
GET http://localhost:8090/api/risk/partidas/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3ODEzNTc0LCJleHAiOjE3MDc4NDk1NzR9.1G55su8c4Rm8N1TrV15kdn6I9ArwEEPRNZvfHry2qXs

##Muestra Partidas crear partida
###

POST http://localhost:8090/api/risk/crearpartida HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3ODEzNTc0LCJleHAiOjE3MDc4NDk1NzR9.1G55su8c4Rm8N1TrV15kdn6I9ArwEEPRNZvfHry2qXs
Content-Type: application/json

{
    "estado_partida": "Espera",
    "num_jugadores": 0
}


##Crear salas vacias
###
POST http://localhost:8090/api/risk/crearsala HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluMyIsImlhdCI6MTcwODA3MTcwMywiZXhwIjoxNzA4MTA3NzAzfQ.K-EF8VOnaP0RIWZq33YVXYyiZh9l9_kihTW98u_yjhA
Content-Type: application/json


{
    "jugador1": 0,
    "jugador2": 0,
    "jugador3": 0,
    "jugador4": 0
}

##Crear zonas vacias
###
POST http://localhost:8090/api/risk/crearzonas HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3ODEzNTc0LCJleHAiOjE3MDc4NDk1NzR9.1G55su8c4Rm8N1TrV15kdn6I9ArwEEPRNZvfHry2qXs
Content-Type: application/json

[
    {
        "jugador_duenyo": 0,
        "descripcion": "Europa"
    },
    {
        "jugador_duenyo": 0,
        "descripcion": "Africa"
    },
    {
        "jugador_duenyo": 0,
        "descripcion": "Asia"
    },
    {
        "jugador_duenyo": 0,
        "descripcion": "Oceania"
    }    
]

##
###
POST http://localhost:8090/api/risk/1/100 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluMyIsImlhdCI6MTcwODA3MTcwMywiZXhwIjoxNzA4MTA3NzAzfQ.K-EF8VOnaP0RIWZq33YVXYyiZh9l9_kihTW98u_yjhA
Content-Type: application/json


    {
        "tropas": 100
    }
